export const measurements = [
	{ label: 'none', value: '' },
	{ label: 'teaspoon', value: 'tsp' },
	{ label: 'tablespoon', value: 'tbsp' },
	{ label: 'fluid ounce', value: 'fl oz' },
	{ label: 'cup', value: 'c' },
	{ label: 'pint', value: 'pt' },
	{ label: 'quart', value: 'qt' },
	{ label: 'gallon', value: 'gal' },
	{ label: 'pound', value: 'lb' },
	{ label: 'ounce', value: 'oz' },
	{ label: 'milligram', value: 'mg' },
	{ label: 'gram', value: 'g' },
	{ label: 'kilogram', value: 'kg' },
	{ label: 'milliliter', value: 'ml' },
	{ label: 'liter', value: 'l' },
	{ label: 'dozen', value: 'doz' },
];
export const fractions = [
	{ label: 'none', value: '' },
	{ label: '¼', value: 0.25 },
	{ label: '⅓', value: 0.33 },
	{ label: '½', value: 0.5 },
	{ label: '⅔', value: 0.67 },
	{ label: '¾', value: 0.75 },
];
export const categories = [
	'Appetizer',
	'Soup',
	'Salad',
	'Vegetable',
	'Main Dish',
	'Side Dish',
	'Bread / Roll',
	'Dessert',
	'Breakfast',
	'Lunch',
	'Dinner',
	'Beef',
	'Poultry',
	'Pork',
	'Seafood',
	'Vegetarian',
	'Holiday',
	'Entertaining',
	'Easy',
	'CrockPot',
	'Bison',
	'Shrimp',
	'Crab',
	'Burger',
	'Chowder',
	'Copycat',
	'Wings',
	'Chicken',
	'Snack',
	'Pasta',
	'Sandwich',
	'Rice',
	'Beans',
	'Sauce / Dressing',
	'Lobster',
	'Taco',
	'Nuts / Seeds',
	'Lamb',
	'Veal',
	'Kangaroo',
	'Sausage',
	'Eggs',
	'Turkey',
	'Duck',
	'Emu',
	'Goose',
	'Tofu',
	'Healthy',
	'Fish',
	'Shellfish',
	'Clams',
	'Noodles',
	'Snail',
	'Crayfish',
	'Salmon',
	'Scallops',
	'Mussels',
	'Squid',
	'Eel',
	'Oysters',
	'Octopus',
	'Tuna',
	'Anchovy',
	'Shark',
	'Sea Cucumber',
	'Uni / Sea Urchin',
	'Roe / Caviar',
	'Jellyfish',
	'Trout',
	'Catfish',
	'Walleye',
	'Cod',
	'Mackerel',
	'Halibut',
	'Kosher',
	'Fruit',
	'Dairy',
	'Cheese',
	'Mushroom',
	'Kebab',
	'Ham',
	'Mutton',
	'Ostrich',
	'Deer',
	'Buffalo',
	'Frog',
	'Rabbit',
	'Squirrel',
	'Herring',
	'Sushi',
	'Dumplings',
	'Halal',
	'Pie',
	'Cake',
	'Pastry',
	'Stew',
	'Organic',
	'Wrap',
	'Burrito',
];
export const mainCategories = [
	'Appetizer',
	'Soup',
	'Salad',
	'Main Dish',
	'Side Dish',
	'Dessert',
	'Breakfast',
	'Lunch',
	'Dinner',
	'Beef',
	'Poultry',
	'Pork',
	'Seafood',
	'Vegetarian',
	'Holiday',
	'Easy',
	'CrockPot',
];
export const substitutions = [
	{
		label: 'Allspice',
		qty: '1 teaspoon',
		sub: '1/2 teaspoon cinnamon, 1/4 teaspoon ginger, and 1/4 teaspoon cloves',
	},
	{
		label: 'Arrowroot starch',
		qty: '1 teaspoon',
		sub: '1 tablespoon flour OR 1 teaspoon cornstarch',
	},
	{ label: 'Baking mix', qty: '1 cup', sub: '1 cup pancake mix' },
	{
		label: 'Baking powder',
		qty: '1 teaspoon',
		sub: '1/4 teaspoon baking soda plus 1/2 teaspoon cream of tartar OR 1/4 teaspoon baking soda plus 1/2 cup buttermilk (decrease liquid in recipe by 1/2 cup)',
	},
	{
		label: 'Baking soda',
		qty: '1 teaspoon',
		sub: '4 teaspoons baking powder OR 1 teaspoon potassium bicarbonate and 1 / 3 teaspoon salt.NOTE: If the recipe calls for an acidic liquid such as sour cream, yogurt, buttermilk, vinegar, molasses, or citrus juice, you should replace it with the same amount of whole milk',
	},
	{
		label: 'Beer',
		qty: '1 cup',
		sub: '1 cup nonalcoholic beer OR 1 cup chicken broth',
	},
	{
		label: 'Brandy',
		qty: '1 / 4 cup',
		sub: '1 teaspoon imitation brandy extract plus enough water to make 1 / 4 cup',
	},
	{
		label: 'Bread crumbs',
		qty: '1 cup',
		sub: '1 cup cracker crumbs OR 1 cup matzo meal OR 1 cup ground oats',
	},
	{
		label: 'Broth: beef or chicken',
		qty: '1 cup',
		sub: '1 bouillon cube plus 1 cup boiling water OR 1 tablespoon soy sauce plus enough water to make 1 cup OR 1 cup vegetable broth',
	},
	{
		label: 'Brown sugar',
		qty: '1 cup, packed',
		sub: "1 cup white sugar plus 1 / 4 cup molasses and decrease the liquid in recipe by 1 / 4 cup OR 1 cup white sugar OR 1 1 / 4 cups confectioners' sugar",
	},
	{
		label: 'Butter(salted)',
		qty: '1 cup',
		sub: '1 cup margarine OR 1 cup shortening plus 1 / 2 teaspoon salt OR 7 / 8 cup vegetable oil plus 1 / 2 teaspoon salt OR 7 / 8 cup lard plus 1 / 2 teaspoon salt',
	},
	{
		label: 'Butter(unsalted)',
		qty: '1 cup',
		sub: '1 cup shortening OR 7 / 8 cup vegetable oil OR 7 / 8 cup lard',
	},
	{
		label: 'Buttermilk',
		qty: '1 cup',
		sub: '1 cup yogurt OR 1 tablespoon lemon juice or vinegar plus enough milk to make 1 cup',
	},
	{
		label: 'Cheddar cheese',
		qty: '1 cup shredded',
		sub: '1 cup shredded Colby cheddar OR 1 cup shredded Monterey Jack cheese',
	},
	{
		label: 'Chervil',
		qty: '1 tablespoon chopped fresh',
		sub: '1 tablespoon chopped fresh parsley',
	},
	{
		label: 'Chicken base',
		qty: '1 tablespoon',
		sub: '1 cup canned or homemade chicken broth or stock. Reduce liquid in recipe by 1 cup',
	},
	{
		label: 'Chocolate (semisweet)',
		qty: '1 ounce',
		sub: '1 (1-ounce) square of unsweetened chocolate plus 4 teaspoons sugar OR 1 ounce semisweet chocolate chips plus 1 teaspoon shortening',
	},
	{
		label: 'Chocolate (unsweetened)',
		qty: '1 ounce',
		sub: '3 tablespoons unsweetened cocoa plus 1 tablespoon shortening or vegetable oil',
	},
	{
		label: 'Cocoa',
		qty: '1/4 cup',
		sub: '1 (1-ounce) square unsweetened chocolate',
	},
	{
		label: 'Condensed cream of mushroom soup',
		qty: '1 (10.75-ounce) can',
		sub: '1 (10.75-ounce) can condensed cream of celery, cream of chicken, or golden mushroom soup',
	},
	{
		label: 'Corn syrup',
		qty: '1 cup',
		sub: '1 1/4 cup white sugar plus 1/3 cup water OR 1 cup honey OR 1 cup light treacle syrup',
	},
	{
		label: 'Cottage cheese',
		qty: '1 cup',
		sub: "1 cup farmer's cheese OR 1 cup ricotta cheese",
	},
	{
		label: 'Cracker crumbs',
		qty: '1 cup',
		sub: '1 cup bread crumbs OR 1 cup matzo meal OR 1 cup ground oats',
	},
	{
		label: 'Cream (half and half)',
		qty: '1 cup',
		sub: '7/8 cup milk plus 1 tablespoon butter',
	},
	{
		label: 'Cream (heavy)',
		qty: '1 cup',
		sub: '1 cup evaporated milk OR 3/4 cup milk plus 1/3 cup butter',
	},
	{
		label: 'Cream (light)',
		qty: '1 cup',
		sub: '1 cup evaporated milk OR 3/4 cup milk plus 3 tablespoons butter',
	},
	{
		label: 'Cream (whipped)',
		qty: '1 cup',
		sub: '1 cup frozen whipped topping, thawed',
	},
	{
		label: 'Cream of tartar',
		qty: '1 teaspoon',
		sub: '2 teaspoons lemon juice or vinegar',
	},
	{
		label: 'Crème fraiche',
		qty: '1 cup',
		sub: 'Combine 1 cup of heavy cream and 1 tablespoon of plain yogurt. Let stand for 6 hours at room temperature',
	},
	{
		label: 'Egg',
		qty: '1 whole (3 tablespoons or 1.7 oz)',
		sub: '2 1/2 tablespoons of powdered egg substitute plus 2 1/2 tablespoons water OR 1/4 cup liquid egg substitute OR 1/4 cup silken tofu pureed OR 3 tablespoons mayonnaise OR half a banana mashed with 1/2 teaspoon baking powder OR 1 tablespoon powdered flax seed soaked in 3 tablespoons water',
	},
	{ label: 'Evaporated milk', qty: '1 cup', sub: '1 cup light cream' },
	{
		label: "Farmer's cheese",
		qty: '8 ounces',
		sub: '8 ounces dry cottage cheese OR 8 ounces creamed cottage cheese, drained',
	},
	{
		label: 'Fats for baking',
		qty: '1 cup',
		sub: '1 cup applesauce OR 1 cup fruit puree',
	},
	{
		label: 'Flour: bread',
		qty: '1 cup',
		sub: '1 cup all-purpose flour plus 1 teaspoon wheat gluten',
	},
	{
		label: 'Flour: cake',
		qty: '1 cup',
		sub: '1 cup all-purpose flour minus 2 tablespoons',
	},
	{
		label: 'Flour: self-Rising',
		qty: '1 cup',
		sub: '7/8 cup all-purpose flour plus 1 1/2 teaspoons baking powder and 1/2 teaspoon of salt',
	},
	{
		label: 'Garlic',
		qty: '1 clove',
		sub: '1/8 teaspoon garlic powder OR 1/2 teaspoon granulated garlic OR 1/2 teaspoon garlic salt, reduce salt in recipe',
	},
	{
		label: 'Gelatin',
		qty: '1 tablespoon, granulated',
		sub: '2 teaspoons agar agar',
	},
	{
		label: 'Ginger (dry)',
		qty: '1 teaspoon',
		sub: '2 teaspoons chopped fresh ginger',
	},
	{
		label: 'Ginger (fresh)',
		qty: '1 teaspoon, minced',
		sub: '1/2 teaspoon ground dried ginger',
	},
	{
		label: 'Green onion',
		qty: '1/2 cup , chopped',
		sub: '1/2 cup chopped onion OR 1/2 cup chopped leek OR 1/2 cup chopped shallots',
	},
	{
		label: 'Hazelnuts',
		qty: '1 cup whole	',
		sub: '1 cup macadamia nuts OR 1 cup almonds',
	},
	{
		label: 'Herbs (fresh)',
		qty: '1 tablespoon chopped fresh',
		sub: '1 teaspoon (chopped or whole leaf) dried herbs',
	},
	{ label: 'Herring', qty: '8 ounces', sub: '8 ounces of sardines' },
	{
		label: 'Honey',
		qty: '1 cup',
		sub: '1 1/4 cup white sugar plus 1/3 cup water OR 1 cup corn syrup OR 1 cup light treacle syrup',
	},
	{
		label: 'Hot pepper sauce',
		qty: '1 teaspoon',
		sub: '3/4 teaspoon cayenne pepper plus 1 teaspoon vinegar',
	},
	{
		label: 'Lard',
		qty: '1 cup',
		sub: '1 cup shortening OR 7/8 cup vegetable oil OR 1 cup butter',
	},
	{
		label: 'Lemon grass',
		qty: '2 fresh stalks',
		sub: '1 tablespoon lemon zest',
	},
	{
		label: 'Lemon juice',
		qty: '1 teaspoon',
		sub: '1/2 teaspoon vinegar OR 1 teaspoon white wine OR 1 teaspoon lime juice',
	},
	{
		label: 'Lemon zest',
		qty: '1 teaspoon',
		sub: '1/2 teaspoon lemon extract OR 2 tablespoons lemon juice',
	},
	{
		label: 'Lime juice',
		qty: '1 teaspoon',
		sub: '1 teaspoon vinegar OR 1 teaspoon white wine OR 1 teaspoon lemon juice',
	},
	{ label: 'Lime zest', qty: '1 teaspoon', sub: '1 teaspoon lemon zest' },
	{
		label: 'Macadamia nuts',
		qty: '1 cup',
		sub: '1 cup almonds OR 1 cup hazelnuts',
	},
	{ label: 'Mace', qty: '1 teaspoon', sub: '1 teaspoon nutmeg' },
	{
		label: 'Margarine',
		qty: '1 cup',
		sub: '1 cup shortening plus 1/2 teaspoon salt OR 1 cup butter OR 7/8 cup vegetable oil plus 1/2 teaspoon salt OR 7/8 cup lard plus 1/2 teaspoon salt',
	},
	{
		label: 'Mayonnaise',
		qty: '1 cup',
		sub: '1 cup sour cream OR 1 cup plain yogurt',
	},
	{
		label: 'Milk (whole)',
		qty: '1 cup',
		sub: '1 cup soy milk OR 1 cup rice milk OR 1 cup water or juice OR 1/4 cup dry milk powder plus 1 cup water OR 2/3 cup evaporated milk plus 1/3 cup water',
	},
	{
		label: 'Mint (fresh)',
		qty: '1/4 cup chopped',
		sub: '1 tablespoon dried mint leaves',
	},
	{
		label: 'Molasses',
		qty: '1 cup',
		sub: 'Mix 3/4 cup brown sugar and 1 teaspoon cream of tartar',
	},
	{
		label: 'Mustard: prepared',
		qty: '1 tablespoon',
		sub: 'Mix together 1 tablespoon dried mustard, 1 teaspoon water, 1 teaspoon vinegar and 1 teaspoon sugar',
	},
	{
		label: 'Onion',
		qty: '1 cup, chopped',
		sub: '1 cup chopped green onions OR 1 cup chopped shallots OR 1 cup chopped leeks OR 1/4 cup dried minced onion OR 1/4 cup onion powder',
	},
	{
		label: 'Orange juice',
		qty: '1 tablespoon',
		sub: '1 tablespoon other citrus juice',
	},
	{
		label: 'Orange zest',
		qty: '1 tablespoon',
		sub: '1/2 teaspoon orange extract OR 1 teaspoon lemon juice',
	},
	{
		label: 'Parmesan cheese',
		qty: '1/2 cup, grated',
		sub: '1/2 cup grated Asiago cheese OR 1/2 cup grated Romano cheese',
	},
	{
		label: 'Parsley',
		qty: '1 tablespoon chopped fresh',
		sub: '1 tablespoon chopped fresh chervil OR 1 teaspoon dried parsley',
	},
	{ label: 'Pepperoni', qty: '1 ounce', sub: '1 ounce salami' },
	{
		label: 'Raisin',
		qty: '1 cup',
		sub: '1 cup dried currants OR 1 cup dried cranberries OR 1 cup chopped pitted prunes',
	},
	{
		label: 'Rice: white',
		qty: '1 cup, cooked',
		sub: '1 cup cooked barley OR 1 cup cooked bulgur OR 1 cup cooked brown or wild rice',
	},
	{
		label: 'Ricotta',
		qty: '1 cup',
		sub: '1 cup dry cottage cheese OR 1 cup silken tofu',
	},
	{
		label: 'Rum',
		qty: '1 tablespoon',
		sub: '1/2 teaspoon rum extract, plus enough water to make 1 tablespoon',
	},
	{ label: 'Saffron', qty: '1/4 teaspoon', sub: '1/4 teaspoon turmeric' },
	{ label: 'Salami', qty: '1 ounce', sub: '1 ounce pepperoni' },
	{
		label: 'Semisweet chocolate chips',
		qty: '1 cup',
		sub: '1 cup chocolate candies OR 1 cup peanut butter or other flavored chips OR 1 cup chopped nuts OR 1 cup chopped dried fruit',
	},
	{
		label: 'Shallots, chopped',
		qty: '1/2 cup',
		sub: '1/2 cup chopped onion OR 1/2 cup chopped leek OR 1/2 cup chopped green onion',
	},
	{
		label: 'Shortening',
		qty: '1 cup',
		sub: '1 cup butter OR 1 cup margarine minus 1/2 teaspoon salt from recipe',
	},
	{
		label: 'Sour cream',
		qty: '1 cup',
		sub: '1 cup plain yogurt OR 1 tablespoon lemon juice or vinegar plus enough cream to make 1 cup OR 3/4 cup buttermilk mixed with 1/3 cup butter',
	},
	{
		label: 'Sour milk',
		qty: '1 cup',
		sub: '1 tablespoon vinegar or lemon juice mixed with enough milk to make 1 cup: Let stand 5 minutes to thicken',
	},
	{
		label: 'Soy sauce',
		qty: '1/2 cup',
		sub: '1/4 cup Worcestershire sauce mixed with 1 tablespoon water',
	},
	{
		label: 'Stock: beef or chicken',
		qty: '1 cup',
		sub: '1 cube beef or chicken bouillon dissolved in 1 cup water',
	},
	{
		label: 'Sweetened condensed milk',
		qty: '1 (14-ounce) can',
		sub: '3/4 cup white sugar mixed with 1/2 cup water and 1 1/8 cups dry powdered milk: Bring to a boil and cook, stirring frequently, until thickened, about 20 minutes',
	},
	{
		label: 'Vegetable oil (for baking)',
		qty: '1 cup',
		sub: '1 cup applesauce OR 1 cup fruit puree',
	},
	{
		label: 'Vegetable oil (for frying)',
		qty: '1 cup',
		sub: '1 cup lard OR 1 cup vegetable shortening',
	},
	{
		label: 'Vinegar',
		qty: '1 teaspoon',
		sub: '1 teaspoon lemon or lime juice OR 2 teaspoons white wine',
	},
	{
		label: 'White sugar',
		qty: '1 cup',
		sub: "1 cup brown sugar OR 1 1/4 cups confectioners' sugar OR 3/4 cup honey OR 3/4 cup corn syrup",
	},
	{
		label: 'Wine',
		qty: '1 cup',
		sub: '1 cup chicken or beef broth OR 1 cup fruit juice mixed with 2 teaspoons vinegar OR 1 cup water',
	},
	{
		label: 'Yeast: active dry',
		qty: '1 (.25-ounce) package',
		sub: '1 cake compressed yeast OR 2 1/2 teaspoons active dry yeast OR 2 1/2 teaspoons rapid rise yeast',
	},
	{
		label: 'Yogurt',
		qty: '1 cup',
		sub: '1 cup sour cream OR 1 cup buttermilk OR 1 cup sour milk',
	},
];
