export const measurements = [
    {label: 'teaspoon', value: 'tsp'},
    {label: 'tablespoon', value: 'tbsp'},
    {label: 'fluid ounce', value: 'fl oz'},
    {label: 'gill', value: 'gill'},
    {label: 'cup', value: 'c'},
    {label: 'pint', value: 'pt'},
    {label: 'quart', value: 'qt'},
    {label: 'gallon', value: 'gal'},
    {label: 'pound', value: 'lb'},
    {label: 'ounce', value: 'oz'},
    {label: 'milligram', value: 'mg'},
    {label: 'gram', value: 'g'},
    {label: 'kilogram', value: 'kg' },
    {label: 'milliliter', value: 'ml'},
    {label: 'liter', value: 'l'},
    {label: 'deciliter', value: 'dl'}
];
export const categories = [
     'Appetizer',
     'Soup',
     'Salad',
     'Vegetable',
     'Main Dish' ,
     'Side Dish',
     'Bread / Roll',
     'Dessert',
     'Breakfast',
     'Lunch',
     'Dinner',
     'Beef',
     'Poultry',
     'Pork',
     'Seafood',
     'Vegetarian',
     'Holiday',
     'Entertaining',
     'Easy',
     'CrockPot',
     'Bison',
     'Shrimp',
     'Crab',
     'Burger',
     'Chowder',
     'Copycat',
     'Wings',
     'Chicken',
     'Snack',
     'Pasta',
     'Sandwich',
     'Rice',
     'Beans',
     'Sauce / Dressing',
     'Lobster',
     'Taco',
     'Nuts / Seeds',
     'Lamb',
     'Veal',
     'Kangaroo',
     'Sausage',
     'Eggs',
     'Turkey',
     'Duck',
     'Emu',
     'Goose',
     'Tofu',
     'Healthy',
     'Fish',
     'Shellfish',
     'Clams',
     'Noodles',
     'Snail',
     'Crayfish',
     'Salmon',
     'Scallops',
     'Mussels',
     'Squid',
     'Eel',
     'Oysters',
     'Octopus',
     'Tuna',
     'Anchovy',
     'Shark',
     'Sea Cucumber',
     'Uni / Sea Urchin',
     'Roe / Caviar',
     'Jellyfish',
     'Trout',
     'Catfish',
     'Walleye',
     'Cod',
     'Mackerel',
     'Halibut',
     'Kosher',
     'Fruit',
     'Dairy',
     'Cheese',
     'Mushroom',
     'Kebab',
     'Ham',
     'Mutton',
     'Ostrich',
     'Deer',
     'Buffalo',
     'Frog',
     'Rabbit',
     'Squirrel',
     'Herring',
     'Sushi',
     'Dumplings',
     'Halal',
     'Pie',
     'Cake',
     'Pastry',
     'Stew',
     'Organic',
     'Wrap',
     'Burrito'
];

/* {name: ''}, */